/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedPlaylistUriRouteImport } from './routes/_authenticated/playlist/$uri'
import { Route as AuthenticatedThemeThemeRouteImport } from './routes/_authenticated/_theme/theme'

const PreviewLazyRouteImport = createFileRoute('/preview')()

const PreviewLazyRoute = PreviewLazyRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/preview.lazy').then((d) => d.Route))
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaylistUriRoute =
  AuthenticatedPlaylistUriRouteImport.update({
    id: '/playlist/$uri',
    path: '/playlist/$uri',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedThemeThemeRoute = AuthenticatedThemeThemeRouteImport.update({
  id: '/_theme/theme',
  path: '/theme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/preview': typeof PreviewLazyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/theme': typeof AuthenticatedThemeThemeRoute
  '/playlist/$uri': typeof AuthenticatedPlaylistUriRoute
}
export interface FileRoutesByTo {
  '/preview': typeof PreviewLazyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/theme': typeof AuthenticatedThemeThemeRoute
  '/playlist/$uri': typeof AuthenticatedPlaylistUriRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/preview': typeof PreviewLazyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_theme/theme': typeof AuthenticatedThemeThemeRoute
  '/_authenticated/playlist/$uri': typeof AuthenticatedPlaylistUriRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preview' | '/auth/callback' | '/theme' | '/playlist/$uri'
  fileRoutesByTo: FileRoutesByTo
  to: '/preview' | '/auth/callback' | '/' | '/theme' | '/playlist/$uri'
  id:
    | '__root__'
    | '/_authenticated'
    | '/preview'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/_theme/theme'
    | '/_authenticated/playlist/$uri'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PreviewLazyRoute: typeof PreviewLazyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/playlist/$uri': {
      id: '/_authenticated/playlist/$uri'
      path: '/playlist/$uri'
      fullPath: '/playlist/$uri'
      preLoaderRoute: typeof AuthenticatedPlaylistUriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_theme/theme': {
      id: '/_authenticated/_theme/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof AuthenticatedThemeThemeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedThemeThemeRoute: typeof AuthenticatedThemeThemeRoute
  AuthenticatedPlaylistUriRoute: typeof AuthenticatedPlaylistUriRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedThemeThemeRoute: AuthenticatedThemeThemeRoute,
  AuthenticatedPlaylistUriRoute: AuthenticatedPlaylistUriRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PreviewLazyRoute: PreviewLazyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
